name: Update Stock Prices

on:
  schedule:
    #- cron: '*/15 * * * *'  # 每X分钟运行一次
    # 上午 9 点到下午 3 点（北京时间）转换为 UTC 是 01:00 - 07:00
    - cron: '*/5 1-7 * * *'
    # 晚上 9 点半到晚上 11 点 55 分（北京时间）转换为 UTC 是 13:30 - 15:55
    - cron: '*/5 13-15 * * *'
    # 晚上 12 点到凌晨 4 点半（北京时间）转换为 UTC 是 16:00 - 20:30
    - cron: '*/5 16-20 * * *'

  workflow_dispatch:        # 允许手动触发
  push:                    # 推送代码时也触发一次，用于测试

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'     # 缓存 pip 依赖
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Run updater
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python stock_updater.py
        
      - name: Upload logs
        if: always()       # 无论成功失败都上传日志
        uses: actions/upload-artifact@v4
        with:
          name: run-logs
          path: |
            *.log
            *.txt
          retention-days: 7
